---
metric_id: metric-google-cloud-pubsub-schema-count
name: Schema Count
metric_type: GAUGE
resource_type: inventory.CloudService:google_cloud.PubSub.Schema
query_options:
  group_by:
    - key: account
      name: Project ID
      search_key: account
    - key: region_code
      name: Region
      search_key: region_code
      reference:
        resource_type: inventory.Region
        reference_key: region_code
    - key: data.schema_type
      name: Schema Type
      search_key: data.schema_type
  fields:
    value:
      operator: count
unit: Count
namespace_id: ns-google-cloud-pubsub-schema
version: '1.1'