---
metric_id: metric-google-cloud-net-lb-count
name: LoadBalancing Count
metric_type: GAUGE
resource_type: inventory.CloudService:google_cloud.Networking.LoadBalancing
query_options:
  group_by:
    - key: region_code
      name: Region
      search_key: region_code
      reference:
        resource_type: inventory.Region
        reference_key: region_code
    - key: account
      name: Project ID
      search_key: account
    - key: data.internal_or_external
      name: Type
      search_key: data.internal_or_external
    - key: data.type
      name: Load Balancer Type
      search_key: data.type
    - key: data.protocol
      name: Protocol
      search_key: data.protocol
  fields:
    value:
      operator: count
unit: Count
namespace_id: ns-google-cloud-networking-loadbalancing
version: '1.1'
