---
metric_id: metric-gcp-pubsub-snapshot-count
name: Snapshot Count
metric_type: GAUGE
resource_type: inventory.CloudService:google_cloud.PubSub.Snapshot
query_options:
  group_by:
    - key: account
      name: Project ID
      search_key: account
    - key: region_code
      name: Region
      search_key: region_code
      reference:
        resource_type: inventory.Region
        reference_key: region_code
    - key: data.state
      name: State
      search_key: data.state
  fields:
    value:
      operator: count
unit: Count
namespace_id: ns-gcp-pubsub-snapshot
version: '1.0'