---
metric_id: metric-gcp-net-eip-count
name: EIP Count
metric_type: GAUGE
resource_type: inventory.CloudService:google_cloud.Networking.ExternalIPAddress
query_options:
  group_by:
    - key: region_code
      name: Region
      search_key: region_code
      reference:
        resource_type: inventory.Region
        reference_key: region_code
    - key: account
      name: Project ID
      search_key: account
    - key: data.status_display
      name: Status
      search_key: data.status_display
    - key: data.address_type
      name: Address Type
      search_key: data.address_type
    - key: data.is_ephemeral
      name: Ephemeral
      search_key: data.is_ephemeral
    - key: data.network_tier
      name: Network Tier
      search_key: data.network_tier
    - key: data.purpose
      name: Purpose
      search_key: data.purpose
    - key: data.ip_version_display
      name: IP Version
      search_key: data.ip_version_display
  fields:
    value:
      operator: count
unit: Count
namespace_id: ns-gcp-networking-eip
version: '1.0'