---
metric_id: metric-google-cloud-net-route-count
name: Route Count
metric_type: GAUGE
resource_type: inventory.CloudService:google_cloud.Networking.Route
query_options:
  group_by:
    - key: region_code
      name: Region
      search_key: region_code
      reference:
        resource_type: inventory.Region
        reference_key: region_code
    - key: account
      name: Project ID
      search_key: account
    - key: data.display.network_display
      name: Network
      search_key: data.display.network_display
    - key: data.display.next_hop
      name: Next Hop
      search_key: data.display.next_hop
  fields:
    value:
      operator: count
unit: Count
namespace_id: ns-google-cloud-networking-route
version: '1.1'