---
cloud_service_group: CloudSQL
cloud_service_type: CloudSQL
name: Count by Project
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            operator: count
options:
  chart_type: DONUT