---
metric_id: metric-gcp-pubsub-subscription-count
name: Subscription Count
metric_type: GAUGE
resource_type: inventory.CloudService:google_cloud.PubSub.Subscription
query_options:
  group_by:
    - key: account
      name: Project ID
      search_key: account
    - key: region_code
      name: Region
      search_key: region_code
      reference:
        resource_type: inventory.Region
        reference_key: region_code
    - key: data.state
      name: State
      search_key: data.state
    - key: data.display.delivery_type
      name: Delivery Type
      search_key: data.display.delivery_type
  fields:
    value:
      operator: count
unit: Count
namespace_id: ns-gcp-pubsub-subscription
version: '1.0'