---
cloud_service_group: ComputeEngine
cloud_service_type: Instance
name: Total Disk Size
query:
  aggregate:
    - unwind:
        path: data.disks
    - group:
        fields:
          - name: value
            key: data.disks.size
            operator: sum
options:
  value_options:
    key: value
    type: size
    options:
      source_unit: GB
      default: 0