---
metric_id: metric-google-cloud-pubsub-topic-sub-count
name: Subscription Count
metric_type: GAUGE
resource_type: inventory.CloudService:google_cloud.PubSub.Topic
query_options:
  group_by:
    - key: account
      name: Project ID
      search_key: account
    - key: region_code
      name: Region
      search_key: region_code
      reference:
        resource_type: inventory.Region
        reference_key: region_code
  fields:
    value:
      key: data.display.subscription_count
      operator: sum
unit: Count
namespace_id: ns-google-cloud-pubsub-topic
version: '1.1'