---
metric_id: metric-google-cloud-ce-ig-in-count
name: Instance Count
metric_type: GAUGE
resource_type: inventory.CloudService:google_cloud.ComputeEngine.InstanceGroup
query_options:
  group_by:
    - key: region_code
      name: Region
      search_key: region_code
      reference:
        resource_type: inventory.Region
        reference_key: region_code
    - key: account
      name: Project ID
      search_key: account
    - key: data.instance_group_type
      name: Instance Group Type
      search_key: data.instance_group_type
    - key: state
      name: State
      search_key: state
    - key: data.autoscaling_display
      name: Autoscaling
      search_key: data.autoscaling_display
    - key: data.autoscaler.mode
      name: Autoscaler Mode
      search_key: data.autoscaler.mode
  fields:
    value:
      key: data.instance_counts
      operator: sum
unit: Count
namespace_id: ns-google-cloud-ce-instance-group
version: '1.1'