---
metric_id: metric-gcp-cf-function-count
name: Function Count
metric_type: GAUGE
resource_type: inventory.CloudService:google_cloud.CloudFunctions.Function
query_options:
  group_by:
    - key: account
      name: Project ID
      search_key: account
    - key: region_code
      name: Region
      search_key: region_code
      reference:
        resource_type: inventory.Region
        reference_key: region_code
    - key: data.state
      name: Function State
      search_key: data.state
      default: true
    - key: data.display.environment
      name: Environment
      search_key: data.display.environment
    - key: data.display.trigger
      name: Trigger
      search_key: data.display.trigger
    - key: data.service_config.ingress_settings
      name: Ingress Settings
      search_key: data.service_config.ingress_settings
    - key: data.build_config.runtime
      name: Runtime
      search_key: data.build_config.runtime
  fields:
    value:
      operator: count
unit: Count
namespace_id: ns-gcp-cloudfunctions-function
version: '1.0'