---
namespace_id: ns-gcp-bigquery-sqlworkspace
name: BigQuery/SQLWorkspace
category: ASSET
provider: google_cloud
icon: 'https://spaceone-custom-assets.s3.ap-northeast-2.amazonaws.com/console-assets/icons/cloud-services/google_cloud/Big_Query.svg'
version: '1.0'