---
namespace_id: ns-google-cloud-ce-machine-image
name: ComputeEngine/MachineImage
category: ASSET
icon: 'https://spaceone-custom-assets.s3.ap-northeast-2.amazonaws.com/console-assets/icons/cloud-services/google_cloud/Compute_Engine.svg'
version: '1.1'
resource_type: inventory.CloudService:google_cloud.ComputeEngine.MachineImage
group: google_cloud